name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
          rustup component add clippy
      - uses: Swatinem/rust-cache@v1
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo clippy --no-deps -- -D clippy::all
